name: 'referrals-analysis'
version: '1.0.0'
config-version: 2

profile: 'referrals-analysis'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  referrals:
    staging:
      +schema: staging
      +materialized: view
      +tags: staging

    marts:
      +schema: marts
      +materialized: table
      +tags: mart

    reporting:
      +schema: reporting
      +materialized: view
      +tags: reporting

seeds:
  referrals:
    sales_people:
      +schema: raw
    referrals:
      +schema: raw
    partners:
      +schema: raw
