version: 2

models:
  - name: dim_partners
    description: >
      Dimension for referrals's partners. It contains detailed information
      about the partners attributes, such as the lead sales name, partner type, country, etc.
    columns:
      - name: partner_id
        description: "Unique identifier of the partner - primary key."
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('stg_partners')
              field: id
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: lead_sales_name
        description: "The name of sales partner."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: partner_type
        description: "Classification of the partner."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: country
        description: "The country where sales partner is based on."
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
          - dbt_expectations.expect_column_values_to_be_null:
              row_condition: "lead_sales_name = 'Potato'"
      - name: created_at
        description: "Timestamp which the partner was created on the system."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
      - name: updated_at
        description: "Timestamp which the partner was updated on the system."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
      - name: ingested_at
        description: "Timestamp which the record was ingested on."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone

  - name: fct_referrals
    description: "Factless fact to track the referrals from GetGround."
    columns:
      - name: referral_id
        description: "Unique identifier of referrals - primary key."
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('stg_referrals')
              field: id
      - name: company_id
        description: "Unique identifier of a company - foreign key."
        tests:
          - not_null
      - name: partner_id
        description: "Unique identifier of a partner - foreign key."
        tests:
          - not_null
          - relationships:
              to: ref('dim_partners')
              field: partner_id
      - name: consultant_id
        description: "Unique identifier of a consultant - foreign key."
        tests:
          - not_null
      - name: lead_sales_name
        description: "The name of lead sales partnership."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: partner_type
        description: "Classification of the partner."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: partner_country
        description: "The country where sales partner is based on."
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: status
        description: "Referral's status."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: is_outbound
        description: >
          is `true` when GetGround refer a customer to a partner (upsell). In this case, the
          partner pays a commission to GetGround.
          is `false` when a partner refer a customer to GetGround. In this case, GetGround pays
          a commission to partner.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
      - name: created_at
        description: "Timestamp which the referral was created on the system."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
      - name: updated_at
        description: "Timestamp which the referral changed the status on the system."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
      - name: ingested_at
        description: "Timestamp which the record was ingested on."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
