version: 2

models:
  - name: stg_portfolio
    description: >
      Information about the promotional offers that are possible to receive, and
      basic information about each one.
    columns:
      - name: offer_channel_key
        description: Unique identifier/Surogate key for each offer.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: offer_id
        description: Unique identifier for each offer.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: reward
        description: Reward given for completing an offer.
        data_type: integer
        data_tests:
          - not_null
      - name: duration
        description: Time in minutes for the offer to be open.
        data_type: integer
        data_tests:
          - not_null
      - name: difficulty_rank
        description: Minimum required spend to complete the offer.
        data_type: integer
        data_tests:
          - not_null
      - name: offer_type
        description: Type of offer.
        data_type: text[]
        data_tests:
          - not_null
          - accepted_values:
              values:
                - bogo
                - discount
                - informational
      - name: channels
        description: A list of channels through which the offer was received.
        data_type: text
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null

  - name: stg_profile
    description: >
      Information about the customers that are part of the promotional offers program.
    columns:
      - name: customer_id
        description: Unique identifier for each customer.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: gender
        description: Gender of the customer.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - M
                - F
                - O
                - N/A
      - name: age
        description: Age of the customer.
        data_type: integer
        data_tests:
          - not_null
      - name: income
        description: Income of the customer.
        data_type: numeric
        data_tests:
          - not_null
      - name: subscribed_date
        description: Date when the customer created an app account.
        data_type: date
        data_tests:
          - not_null
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null

  - name: stg_transcript
    description: >
      Information about the different steps of promotional offers that a customer receives. It also
      contains information about the transactions that the customer makes.
    columns:
      - name: transaction_id
        description: Unique identifier for each transaction.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: customer_id
        description: Unique identifier for each customer.
        data_type: text
        data_tests:
          - not_null
      - name: offer_id
        description: Unique identifier for each offer.
        data_type: text
      - name: transaction_type
        description: Type of event. Can be offer received, offer viewed, transaction, or offer completed.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - offer received
                - offer viewed
                - transaction
                - offer completed
      - name: reward
        description: Reward given for completing an offer.
        data_type: integer
      - name: amount
        description: Amount spent by the customer.
        data_type: integer
      - name: hours_since_start
        description: Time in hours since the start of the test.
        data_type: integer
        data_tests:
          - not_null
      - name: days_since_start
        description: Time in days since the start of the test.
        data_type: integer
        data_tests:
          - not_null
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null
