name: 'layoffs_analysis'
version: '1.0.0'
config-version: 2

profile: 'layoffs_analysis'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  layoffs:
    staging:
      +schema: staging
      +tags: staging

seeds:
  layoffs:
    +schema: raw