version: 2

models:
  - name: completed_offer_agg_channel
    description: >
      This model aggregates the completed offers by channel.
    columns:
      - name: completed_offer_agg_channel_key
        description: The surrogate key of the model.
        data_type: integer
        data_tests:
          - unique
          - not_null
      - name: channel
        description: The channel of the offer.
      - name: total_completed_transactions
        description: The number of completed offers by channel.
        data_type: integer
      - name: ingested_at
        description: The timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null

  - name: completed_offer_agg_reward
    description: >
      This model aggregates the completed offers by reward.
    columns:
      - name: completed_offer_agg_reward_key
        description: The surrogate key of the model.
        data_type: integer
        data_tests:
          - unique
          - not_null
      - name: reward
        description: The reward of the offer.
      - name: total_completed_transactions
        description: The number of completed offers by reward.
        data_type: integer
      - name: ingested_at
        description: The timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null

  - name: completed_offer_agg_duration
    description: >
      This model aggregates the completed offers by duration.
    columns:
      - name: completed_offer_agg_duration_key
        description: The surrogate key of the model.
        data_type: integer
        data_tests:
          - unique
          - not_null
      - name: duration
        description: The duration of the offer.
      - name: total_completed_transactions
        description: The number of completed offers by duration.
        data_type: integer
      - name: ingested_at
        description: The timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null

  - name: completed_offer_agg_type
    description: >
      This model aggregates the completed offers by type.
    columns:
      - name: completed_offer_agg_type_key
        description: The surrogate key of the model.
        data_type: integer
        data_tests:
          - unique
          - not_null
      - name: type
        description: The type of the offer.
      - name: total_completed_transactions
        description: The number of completed offers by type.
        data_type: integer
      - name: ingested_at
        description: The timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null
