version: 2

models:
  - name: stg_distribution_centers
    description: Information about distribution centers.
    columns:
      - name: distribution_center_id
        description: Unique identifier for each distribution center.
      - name: name
        description: Name of the distribution center.
      - name: latitude
        description: Latitude coordinate of the distribution center.
      - name: longitude
        description: Longitude coordinate of the distribution center.
      - name: localization_point
        description: Geography localization point of the distribution center.
      - name: ingested_at
        description: Timestamp indicating when the record was ingested.

  - name: stg_events
    description: Information about user interaction on e-commerce website.
    columns:
      - name: event_id
        description: Unique identifier for each event.
      - name: session_id
        description: Identifier for the session during which the event occured.
      - name: user_id
        description: Identifier for the user associated with the event.
      - name: event_sequence_number
        description: Sequence number of the event.
      - name: event_type
        description: Type of event recorded.
      - name: ip_address
        description: IP address from which the event originated.
      - name: browser
        description: Web browser used during the event
      - name: traffic_source
        description: Source of the traffic leading to the event
      - name: uri
        description: Uniform Resource Identifier assoaciated with the event.
      - name: city
        description: City where the event occurred.
      - name: state
        description: State where the event occurred.
      - name: postal_code
        description: Postal code of the event location.
      - name: created_at
        description: Timestamp indicating when the event took place.
      - name: ingested_at
        description: Timestamp indicating when the record was ingested.

  - name: stg_inventory_items
    description: Information about inventory items.
    columns:
      - name: inventory_item_id
        description: Unique identifier for each inventory item.
      - name: product_id
        description: Identifier for the associated product.
      - name: distribution_center_id
        description: Unique identifier for the distribution center associated with the product.
      - name: product_sku
        description: Stock Keeping Unit of the product.
      - name: product_category
        description: Category of the associated product.
      - name: product_name
        description: Name of the associated product.
      - name: product_brand
        description: Brand of the associated product.
      - name: product_retail_price
        description: Retail price of the associated product.
      - name: product_department
        description: Department to which the product belongs.
      - name: cost
        description: Cost of the inventory item.
      - name: created_at
        description: Timestamp indicating when the inventory item was created.
      - name: sold_at
        description: Timestamp indicating when the inventory item was sold.
      - name: ingested_at
        description: Timestamp indicating when the record was ingested.

  - name: stg_order_items
    description: Information about Order items.
    columns:
      - name: order_item_id
        description: Unique identifier for each order item.
      - name: order_id
        description: Identifier for the associated order.
      - name: user_id
        description: Identifier for the user who placed the order.
      - name: product_id
        description: Identifier for the associated product.
      - name: inventory_item_id
        description: Identifier for the associated inventory item.
      - name: status
        description: Status of the order item.
      - name: sale_price
        description: Price of the order item.
      - name: created_at
        description: Timestamp indicating when the order item was created.
      - name: shipped_at
        description: Timestamp indicating when the order item was shipped.
      - name: delivered_at
        description: Timestamp indicating when the order item was delivered.
      - name: returned_at
        description: Timestamp indicating when the order item was returned.
      - name: ingested_at
        description: Timestamp indicating when the record was ingested.

  - name: stg_orders
    description: Information about the orders.
    columns:
      - name: order_id
        description: Unique identifier for each order.
      - name: user_id
        description: Identifier for the user who placed the order.
      - name: status
        description: Status of the order.
      - name: gender
        description: Gender information of the user.
      - name: num_of_item
        description: Number of items in the order
      - name: created_at
        description: Timestamp indicating when the order was created.
      - name: shipped_at
        description: Timestamp indicating when the order was shipped.
      - name: delivered_at
        description: Timestamp indicating when the order was delivered.
      - name: returned_at
        description: Timestamp indicating when the order was returned.
      - name: ingested_at
        description: Timestamp indicating when the record was ingested.

  - name: products
    description: Information about the products.
    columns:
      - name: product_id
        description: Unique identifier for each product.
      - name: distribution_center_id
        description: Identifier for the distribution center associated with the product.
      - name: product_sku
        description: Stock Keeping Unit of the product.
      - name: product_category
        description: Category to which the product belongs.
      - name: product_department
        description: Department to which the product belongs.
      - name: product_name
        description: Name of the product.
      - name: product_brand
        description: Brand of the product.
      - name: product_retail_price
        description: Retail price of the product.
      - name: cost
        description: Cost of the product.
      - name: ingested_at
        description: Timestamp indicating when the record was ingested.

  - name: stg_users
    description: Information about the users.
    columns:
      - name: user_id
        description: Unique identifier for each user.
      - name: first_name
        description: First name of the user.
      - name: last_name
        description: Last name of the user.
      - name: age
        description: Age of the user.
      - name: gender
        description: Gender of the user.
      - name: traffic_source
        description: Source of the traffic leading to the user.
      - name: email
        description: Email address of the user.
      - name: country
        description: Country where the user is located.
      - name: state
        description: State where the user is located.
      - name: city
        description: City where the user is lcoated.
      - name: street_address
        description: Street address of the user.
      - name: postal_code
        description: Postal code of the user.
      - name: latitude
        description: Latitude coordinate of the user.
      - name: longitude
        description: Longitude coordinate of the user.
      - name: localization_point
        description: Geography localization point of the user.
      - name: created_at
        description: Timestamp indicating when the user account was created.
      - name: ingested_at
        description: Timestamp indicating when the record was ingested.
