version: 2

models:
  - name: dim_date
    description: Dimension table about the date.
    columns:
      - name: date_key
        description: Unique identifier for each date.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: date_day
        description: Date.
      - name: prior_date_day
        description: Date of the previous day.
      - name: next_date_day
        description: Date of the next day.
      - name: prior_year_date_day
        description: Date of the same day in the previous year.
      - name: prior_year_over_year_date_day
        description: Date of the same day in the year before the previous year.
      - name: day_of_week
        description: Day of the week.
      - name: day_of_week_name
        description: Name of the day of the week.
      - name: day_of_week_name_short
        description: Short name of the day of the week.
      - name: day_of_month
        description: Day of the month.
      - name: day_of_year
        description: Day of the year.
      - name: week_start_date
        description: Start date of the week.
      - name: week_end_date
        description: End date of the week.
      - name: prior_year_week_start_date
        description: Start date of the week in the previous year.
      - name: prior_year_week_end_date
        description: End date of the week in the previous year.
      - name: week_of_year
        description: Week of the year.
      - name: iso_week_start_date
        description: Start date of the ISO week.
      - name: iso_week_end_date
        description: End date of the ISO week.
      - name: prior_year_iso_week_start_date
        description: Start date of the ISO week in the previous year.
      - name: prior_year_iso_week_end_date
        description: End date of the ISO week in the previous year.
      - name: iso_week_of_year
        description: ISO week of the year.
      - name: prior_year_week_of_year
        description: Week of the year in the previous year.
      - name: prior_year_iso_week_of_year
        description: ISO week of the year in the previous year.
      - name: month_of_year
        description: Month of the year.
      - name: month_name
        description: Name of the month.
      - name: month_name_short
        description: Short name of the month.
      - name: month_start_date
        description: Start date of the month.
      - name: month_end_date
        description: End date of the month.
      - name: prior_year_month_start_date
        description: Start date of the month in the previous year.
      - name: prior_year_month_end_date
        description: End date of the month in the previous year.
      - name: quarter_of_year
        description: Quarter of the year.
      - name: quarter_start_date
        description: Start date of the quarter.
      - name: quarter_end_date
        description: End date of the quarter.
      - name: year_number
        description: Year number.
      - name: year_start_date
        description: Start date of the year.
      - name: year_end_date
        description: End date of the year.
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null

  - name: dim_customer
    description: >
      Dimension table about the customers that are part of the promotional offers program.
    columns:
      - name: customer_id
        description: Unique identifier for each customer.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: gender
        description: Gender of the customer.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - M
                - F
                - O
                - N/A
      - name: age
        description: Age of the customer.
        data_type: integer
        data_tests:
          - not_null
      - name: income
        description: Income of the customer.
        data_type: numeric
        data_tests:
          - not_null
      - name: subscribed_date
        description: Date when the customer created an app account.
        data_type: date
        data_tests:
          - not_null
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null

  - name: dim_offer
    description: >
      Dimension table about the promotional offers that are part of the promotional offers program.
    columns:
      - name: offer_channel_key
        description: Unique identifier/surrogate key for each offer-channel combination.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: offer_id
        description: Unique identifier for each offer.
        data_type: text
      - name: offer_type
        description: Type of offer.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - bogo
                - discount
                - informational
      - name: channel
        description: A list of channels through which the offer was received.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - email
                - mobile
                - social
                - web
      - name: difficulty_rank
        description: Minimum spending required to complete an offer.
        data_type: integer
        data_tests:
          - not_null
      - name: reward
        description: Reward given upon completion of the offer.
        data_type: numeric
        data_tests:
          - not_null
      - name: duration
        description: Time in minutes for the offer to be open.
        data_type: integer
        data_tests:
          - not_null
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null

  - name: fact_customer_journey
    description: >
      Fact table about the customer journey through the promotional offers program.
    columns:
      - name: customer_journey_key
        description: Unique identifier for each customer journey.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: transaction_id
        description: Unique identifier for each transaction.
        data_type: text
        data_tests:
          - not_null
      - name: customer_id
        description: Unique identifier for each customer.
        data_type: text
        data_tests:
          - not_null
      - name: offer_id
        description: Unique identifier for each offer.
        data_type: text
      - name: gender
        description: Gender of the customer.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - M
                - F
                - O
                - N/A
      - name: age
        description: Age of the customer.
        data_type: integer
        data_tests:
          - not_null
      - name: income
        description: Income of the customer.
        data_type: numeric
        data_tests:
          - not_null
      - name: customer_subscribed_date
        description: Date when the customer created an app account.
        data_type: date
        data_tests:
          - not_null
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null
  - name: fact_offer_performance
    description: >
      Fact table about the performance of the promotional offers program.
    columns:
      - name: offer_performance_key
        description: Unique identifier for each offer performance.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: offer_id
        description: Unique identifier for each offer.
        data_type: text
      - name: transaction_id
        description: Unique identifier for each transaction.
        data_type: text
        data_tests:
          - not_null
      - name: offer_type
        description: Type of offer.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - bogo
                - discount
                - informational
      - name: offer_channel
        description: A list of channels through which the offer was received.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - email
                - mobile
                - social
                - web
      - name: offer_difficulty_rank
        description: Minimum spending required to complete an offer.
        data_type: integer
        data_tests:
          - not_null
      - name: offer_duration
        description: Time in minutes for the offer to be open.
        data_type: integer
        data_tests:
          - not_null
      - name: offer_reward
        description: Reward given upon completion of the offer.
        data_type: numeric
        data_tests:
          - not_null
      - name: offer_status
        description: Status of the offer.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - received
                - viewed
                - completed
      - name: hours_since_start
        description: Time in hours since the offer was received.
        data_type: numeric
        data_tests:
          - not_null
      - name: days_since_start
        description: Time in days since the offer was received.
        data_type: numeric
        data_tests:
          - not_null
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null

  - name: customer_profile_received_offer
    description: >
      Model about the customer profile when an offer is received.
    columns:
      - name: customer_profile_received_offer_key
        description: Unique identifier for each customer profile when an offer is received.
        data_type: text
        data_tests:
          - not_null
          - unique
      - name: customer_id
        description: Unique identifier for each customer.
        data_type: text
        data_tests:
          - not_null
      - name: offer_id
        description: Unique identifier for each offer.
        data_type: text
      - name: gender
        description: Gender of the customer.
        data_type: text
        data_tests:
          - not_null
          - accepted_values:
              values:
                - M
                - F
                - O
                - N/A
      - name: age
        description: Age of the customer.
        data_type: integer
        data_tests:
          - not_null
      - name: income
        description: Income of the customer.
        data_type: numeric
        data_tests:
          - not_null
      - name: subscribed_date
        description: Date when the customer created an app account.
        data_type: date
        data_tests:
          - not_null
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null
