version: 2

macros:
  - name: customer_profile_by_transaction_type
    description: >
      This macro returns a customer profile based on the transaction type.
    arguments:
      - name: transaction_type
        type: String
        description: The transaction type to filter the customer profile by.
      - name: surrogate_key_columns
        type: Array
        description: >
          The surrogate key columns to use for the customer profile.
      - name: surrogate_key_name
        type: String
        description: >
          The surrogate key column name to use for the customer profile.

  - name: completed_offers_agg_by
    description: >
      This macro returns the completed offers aggregated by the specified columns.
    arguments:
      - name: agg_column
        type: String
        description: The column to aggregate the completed offers by.
      - name: new_column_name
        type: String
        description: The new column name for the aggregated completed offers.
      - name: surrogate_column_name
        type: String
        description: The surrogate column name to use for the completed offers.
