version: 2

sources:
  - name: the-look-e-commerce
    database: bigquery-public-data
    schema: thelook_ecommerce
    description: TheLook is a fictitious eCommerce clothing site developed by the Looker team.
    tables:
      - name: distribution_centers
        description: 
      - name: events
      - name: inventory_items
      - name: order_items
      - name: orders
      - name: products
      - name: users
